-- AlterTable
ALTER TABLE "users" ALTER COLUMN "email" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "first_name" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "other_name" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "password" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "surname" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "phone_number" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "role" SET DATA TYPE VARCHAR(50);
