version: "3.9"
service:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Pielly16
      POSTGRES_USER: postgres
      POSTGRES_DB: adakadan
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 30s
      retries: 5
    ports:
      - "5432:5432"
    volume:
      -./pg_data:/var/lib/postgresql/data
