version: "3.7"
services:
  adakadan:
    build: .
    image: adakan-user-management-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    command: ["yarn", "start"]
    ports:
    - "3000:3000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Pielly16
      POSTGRES_USER: postgres
      POSTGRES_DB: adakadan
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 30s
      retries: 5
    ports:
      - "5432:5432"
